/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
}
